server.port=8181
server.servlet.context-path=/workflow
#jsp
spring.mvc.view.prefix=/webapp/
spring.mvc.view.suffix=.jsp
#using Bean
spring.main.allow-bean-definition-overriding=true
#debug=true
#超时则登出，单位s
server.servlet.session.timeout=600

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
##################################这里面配置jpa#####################################
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.datasource.hikari.auto-commit=true
spring.jpa.properties.hibernate.allow_update_outside_transaction=true
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
.sql
# create and drop tables and sequences, loads import.sql
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=false
#spring.jpa.database=oracle
##################################这里面配置oracle数据库#####################################
host=127.0.0.1
spring.datasource.oracle.driver=oracle.jdbc.driver.OracleDriver
spring.datasource.oracle.jdbc-url=jdbc:oracle:thin:@${host}:1521:mm
spring.datasource.oracle.username=les
#ENC(RKQj7K8g0wAjGg7DGMmt8w==)
spring.datasource.oracle.password=6666
#ENC(/+IDm4x6ioK4koWfWpROWQ==)
##################################这里面配置mysql数据库#####################################
#spring.datasource.mysqlDataSource.jdbc-url=jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf8&useSSL=false
#spring.datasource.mysqlDataSource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.mysqlDataSource.username=les
#spring.datasource.mysqlDataSource.password=6666
##################################这里面配置sqlserver数据库#####################################
spring.datasource.sqlserverDataSource.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.sqlserverDataSource.jdbc-url=jdbc:sqlserver://localhost:1433;DatabaseName=mm
spring.datasource.sqlserverDataSource.username=les
spring.datasource.sqlserverDataSource.password=6666
###################################文件传输配置#####################################
#开启文件上传与下载
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# 最重要的是这一行，也可以设置 -1 不限制
server.tomcat.max-swallow-size=100MB
#自定义上传文件路径
file.upload.dir=d:/MMLES/folder/
#自定义上传文件类型
#file.upload.disableTyple=pdf,docx
###################################加密与解密#####################################
//数据库加密
#jasypt.encryptor.proxyPropertySources=true
#jasypt.encryptor.bean=encryptorBean
jasypt.encryptor.password=fangpengcheng@mail.tsinghua.edu.cn
jasypt.encryptor.algorithm=PBEWithMD5AndDES
##  #PBEWITHHMACSHA512ANDAES_256 它是 sha512 加 AES 高级加密，需要 Java JDK 1.9 及以上支持
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

########################################腾讯即是工具IM#################################################
##李化伟得应用
#IMConfig.sdkAppId=1400757520
#IMConfig.expireTime=604800
#IMConfig.secretKey="a784f121b70e2d81dcf7b261109068c48579be04412e20fc4b88a73085b11820"
#自己的应用
IMConfig.sdkAppId=1400759804
IMConfig.expireTime=604800
IMConfig.secretKey=119e51fc4ac41fffd697afc05d9474eb9bcfb18f50ac665859591c0a1a1dc050

########################################前端路径#################################################
frontendUrl=http://localhost:8080/#/
#frontendUrl=http://les88.picp.vip/#/