
#host=182.92.174.224
#host=192.168.99.100
#host=10.216.70.234
#host=82.157.150.222
host=127.0.0.1
#jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc:mysql://${host}:3306/avic
#jdbc.url=jdbc:mysql://${host}:10556/ys
jdbc.url=jdbc:oracle:thin:@${host}:1521:mm
#jdbc.username=liaoqm
#jdbc.password=YSProject2015-1
#jdbc.username=root
#jdbc.password=ys15902930591
jdbc.username=mms_s
jdbc.password=cape


#spring.datasource.url=jdbc:oracle:thin:@10.216.40.94:1521:aps
#spring.datasource.username=mms
#spring.datasource.password=cape
------------------------------------------
#-----------------------------------------------------
# c3p0
#-----------------------------------------------------
#idleConnectionTestPeriod
jdbc.c3p0.testConnectionOnCheckout=false
jdbc.c3p0.testConnectionOnCheckin=true
jdbc.c3p0.idleConnectionTestPeriod=3600
#-----------------------------------------------------
# c3p0
#-----------------------------------------------------
#initialPoolSize, minPoolSize, maxPoolSize define the number of Connections that will be pooled.
#Please ensure that minPoolSize <= maxPoolSize.
#Unreasonable values of initialPoolSize will be ignored, and minPoolSize will be used instead.
jdbc.c3p0.initialPoolSize=10
jdbc.c3p0.minPoolSize=10
jdbc.c3p0.maxPoolSize=100
#maxIdleTime defines how many seconds a Connection should be permitted to go unused before being culled from the pool.
jdbc.c3p0.maxIdleTime=3600


